name: main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup project
        run: make setup

      - name: run linter
        run: make lint

      - name: run tests
        run: make test


